### PR TITLE
Added Quickorder

### PR DESCRIPTION
**Pull request by Popesites**

### CODE REVIEW

**Comment by Popesites** [comment]
Hi! Would love to talk with somebody you David about this module if you have any questions. We have recently released this extension, and are looking to start sharing it with the public.

**Comment by DavidLambauer** [comment]
Hi @Popesites, thank you for your PR. I will come back to you after I checked the module.

**Comment by Popesites** [comment]
Hey David,

I appreciate the direction you left in your comment above. Let us take care of these recommendations, and when we update the master repo, I will comment on this thread.

Thanks!

Have a good day.

**Comment by Popesites** [comment]
@DavidLambauer can you please clarify what you mean by:

> Use a style guide

**Comment by Popesites** [comment]
@DavidLambauer can you please clarify what you mean by:

> Use a style guide

**Comment by nfourteen** [comment]
@Popesites Info on style guides: [http://www.phptherightway.com/#code_style_guide](http://www.phptherightway.com/#code_style_guide)

**Comment by DavidLambauer** [comment]
Hi @Popesites, as @nfourteen mentioned, a code style helps other developers to dig into the code easier. Using doc blocks, for example, will improve the experience with an IDE like PhpStorm.

**Comment by Popesites** [comment]
Got it @nfourteen and @DavidLambauer - thanks for pointing that out! I will review your pull request on the quickorder repo and make sure we implement a style guide for the rest of the extension.

**Comment by Popesites** [comment]
@DavidLambauer we have made a code push that addressed your concerns. When you get time, please review. Thank you!

**Comment by Popesites** [comment]
@DavidLambauer tests were added.

**Comment by DavidLambauer** [comment]
Thank you, I'll review it later and add it to the awesome list

**Pull request merged**
