### PR TITLE
adding MUP

### PR DESCRIPTION
**Pull request by npoole-commer**
I'll yield to your experience if this item is worthy of the list.  My coworkers and I use it for m2 all day every day :)

### CODE REVIEW

**Comment by DavidLambauer** [comment]
I didn't found the time to test it yet, but it look great. Why don't we leave this open

**Comment by npoole81** [comment]
i got shy ;)

**Comment by DavidLambauer** [comment]
no need to ;). So do you have some kind of a Magento 2 specific config for MUP?

**Comment by npoole81** [comment]
the default is a good starting point.  covers all the basic we all run (setup:upgrade, setup:di, etc)

**Comment by DavidLambauer** [comment]
I had a deeper look at it. Nice little tool, should be worth to be in the list

**Pull request merged**
